FROM python:3.7.8-slim AS base

WORKDIR /root/
COPY src/* src/
COPY setup.py .
COPY setup.cfg .
COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install .

FROM base AS backend

WORKDIR /root/src/examples/mnist
# RUN pip freeze
CMD [ "python", "mnist_fed_avg_server.py"]